CompileFlags:
  Add: [-Wall]
  Remove: [-W*]
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc, -std=c11]
  Compiler: gcc
---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add: [-xc++, -std=c++23]
  Compiler: g++
